parameters:
  imt_data_grid.factory.class: IMT\DataGrid\Factory\Factory

  imt_data_grid.registry.class: IMT\DataGrid\Registry\Registry

  imt_data_grid.request.class: IMT\DataGridBundle\HttpFoundation\Request

services:
  imt_data_grid.factory:
    class: %imt_data_grid.factory.class%
    arguments:
      - @imt_data_grid.request
      - @imt_data_grid.registry
      - @templating

  imt_data_grid.registry:
    class: %imt_data_grid.registry.class%
    public: false

  imt_data_grid.request:
    class: %imt_data_grid.request.class%
    public: false
    scope: request
    arguments:
      - @request