parameters:
  imt_data_grid.manager.class: IMT\DataGrid\Manager\Manager

services:
  imt_data_grid.manager:
    class: %imt_data_grid.manager.class%
    arguments:
      - @event_dispatcher
      - @templating